config/routes.rb
Awaweb::Application.routes.draw do
  
  get "oauth2/start"

  get "oauth2/callback"

  namespace(:api) do
    namespace(:v1) do
      resources :users
      resources :refills
      resources :datas
      resources :ads
      match 'refills/new/:id/:type' => 'refills#new'
      
    end
  end
  
  devise_for :users

  get "dashboard/index"

  get "dashboard/group"

  get "auth/login"

  get "auth/logout"

  resources :groups

  resources :bottles

  resources :users

  root :to => "dashboard#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #require 'oauth2'

  before_filter :authenticate_user!
   
  def index
    
    @user = current_user
    @validate = FALSE
    if @user.bottles.count > 0
      @validate = TRUE
      @bottle = @user.bottles.first
      range = "created_at #{(1.day.ago.utc...Time.now.utc).to_s(:db)} AND bottle_id = #{@bottle.id}"
      @today = Refill.all(:conditions => range)
      @alltime = Refill.all(:conditions => "bottle_id = #{@bottle.id}")
      if @today.length > 0
        @daily = ((0.8 * @today.length) / 1.5 ) * 100  
      end
      
      if @alltime.length > 0
        @money = @alltime.length * 0.3
        @garbage = @alltime.length * 0.2 
      end
    end
    
  end

  def stats
  end
  
  def points
  end
  
  def group
    
    @client = OAuth2::Client.new('ZJY05SESKHGDZCUZVL3SMESD3YWRUEGMFPAFLKUNGGUVUZIX', 'WZ0R1KA53LRLPRSOSGOGXZE1DCZGLSMEUUEFHYUQWYN2YFFG',
          :site => ' http://foursquare.com',
          :request_token_path => "/oauth2/request_token",
          :access_token_path  => "/oauth2/access_token",
          :authorize_path     => "/oauth2/authenticate?response_type=code",
          :parse_json => true)
          
    redirect_to @client.web_server.authorize_url(
          :redirect_uri => "http://localhost:3000/oauth2/callback"
        )
    #@client.auth_code.authorize_url(:redirect_uri => 'http://localhost:8080/oauth2/callback')
    # => "https://example.org/oauth/authorization?response_type=code&client_id=client_id&redirect_uri=http://localhost:8080/oauth2/callback"

    #token = @client.auth_code.get_token('authorization_code_value', :redirect_uri => 'http://localhost:8080/oauth2/callback')
    
    #response = token.get('/api/resource', :params => { 'query_foo' => 'bar' })
    #response.class.name
    # => OAuth2::Response
    
  end

  def buy
  end
  
  def order
  end
 
  def charity
  end

  def map
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_newsignup.html.erb
<div id="newsignup">
	
	<p><h1>THANK YOU for signing up !</h1>&nbsp;<br/></p>
	
	<div id="button-wrapper">
		<a href="/bottles/new"><div class="button left">
		&nbsp;<br/>&nbsp;<br/>I HAVE A BOTTLE, LET'S ADD IT !
	</div></a>
	<a href="/dashboard/buy">
	<div class="button">
		&nbsp;<br/>I DON'T HAVE A BOTTLE, LET'S BUY ONE !
	</div></a>
	</div>
</div>

app/views/dashboard/_withBottle.html.erb
<% content_for :javascript do %>
<script src="/javascripts/raphael-min.js"></script>
<script>
window.onload = function () {
	
	var html2 = document.getElementById("counter");
	var pour = 0;
	
	function updatepour(value) {
		html2.innerHTML = value + "%";
	}

	(function () {
		
		if(pour <= <%= @daily %>){
		updatepour(pour);
		pour +=1;
		setTimeout(arguments.callee, 50);
		
	}
		})();
};
</script>

<% end %>

<% content_for :menu do %>

	<div id="menu">
		<a href="/"><div class="item">
			<h1>how are you doing?</h1>
			see your consumption
		</div></a>
		<a href="/dashboard/charity"><div class="item">
			<h1>help us to help!</h1>
			donate
		</div></a>
		<a href="/users/edit"><div class="item">
			<h1>changes?</h1>
			edit your data
		</div></a>
		<a href="/dashboard/map"><div class="item">
			<h1>where to fill the bottle?</h1>
			map and iPhone app
		</div></a>
	</div>

<% end %>
<div id="dash-left">
	
<h1>Hi, <%= @user.surname + " " + @user.name %>, WELCOME !</h1>

<p><strong>Your water consumption:</strong></p>
<p> - Today : <%= @today.length.to_s %> fills<br/>
	- Total : <%= @alltime.length.to_s %> fills<br/>
</p>
&nbsp;<br/>

<p><strong>Every fill makes a difference.</strong> With your total of <%= @alltime.length.to_s %> fills you have saved (compared to the same amount of water bought in plastic bottles):</p>
&nbsp;<br/>&nbsp;<br/>
 <div id="summary">
  		<div>
  	<%= image_tag "money.png" %><br/><%= @money %>€
  </div>

	<div>
  	<%= image_tag "waste.png" %><br/><%= @garbage %> bags of bottle waste.
  </div>

</div>
&nbsp;<br/>&nbsp;<br/>

<p>
<strong>You have donated to UNICEF.</strong> Read more how have you helped.
Check this page to find the nearest fountain or download and iPhone App to do it for you.</p>
<p>
</div></p>

<div id="dash-right">
	<p><strong>Today you have consumed : </strong></p>
	<div id="counter">
		0%
	</div>
</div>

<% content_for :logout do %>
<div id="logout">
<strong><%= @user.surname + " " + @user.name %></strong> is logged in. <%= link_to('LOG OUT', destroy_user_session_path) %>
</div>
<% end %>

<% content_for :like do %>
<div id="like">
	<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=208754232497527&amp;xfbml=1"></script><fb:like href="http://awaweb.heroku.com" send="true" width="450" show_faces="false" font="arial"></fb:like>
</div>
<% end %>

<% content_for :twitter do %>
<div id="twitter">
	<a href="http://twitter.com/share" class="twitter-share-button" data-url="http://awaweb.heroku.com" data-text="I have saved <%= @garbage %> plastic bags waste using Main Stream network !" data-count="none">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</div>
<% end %>

<!--<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
-->

app/views/dashboard/charity.html.erb
<% content_for :menu do %>

	<div id="menu">
		<a href="/"><div class="item">
			<h1>how are you doing?</h1>
			see your consumption
		</div></a>
		<a href="/dashboard/charity"><div class="item">
			<h1>help us to help!</h1>
			donate
		</div></a>
		<a href="/users/edit"><div class="item">
			<h1>changes?</h1>
			edit your data
		</div></a>
		<a href="/dashboard/map"><div class="item">
			<h1>where to fill the bottle?</h1>
			map and iPhone app
		</div></a>
	</div>

<% end %>
<div id="donate">
	
<h1>HELP US TO HELP! Every fill makes a difference.</h1>

<p>Be a benefactor and donate while using MAINSTREAM. Every fill makes a difference and every fill can help us to help. By donating to these following purposes you can change the world.</p>

<p>Want to communicate your donations to others? We will send you a ribbon of your donation cause, which you can put around the bottle. This is a great way to show others that you care!</p>

<p><strong>Current donation options:</strong></p>
<%= image_tag "charity/wwf.jpg", :class => "association" %>
<%= image_tag "charity/world.jpg", :class => "association" %>
<%= image_tag "charity/red.png", :class => "association" %>
<%= image_tag "charity/plan.jpg", :class => "association" %>
<%= image_tag "charity/pink-ribbon.jpg", :class => "association" %>


</div>

app/views/dashboard/group.html.erb
<h1>Dashboard#group</h1>
<p>Find me in app/views/dashboard/group.html.erb</p>

app/views/dashboard/index.html.erb
<% if @validate %>

<%= render :partial => 'withBottle' %>
<% else %>
<%= render :partial => 'newsignup' %>
<% end %>

app/views/dashboard/map.html.erb
<% content_for :javascript do %>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

var map;
var marker;
var image = '/images/drop.png';

var markers = [];

var foutains = [
    new google.maps.LatLng(37.42717,-122.168666),
    new google.maps.LatLng(37.426122,-122.172765),
    new google.maps.LatLng(37.425696,-122.170994),
	new google.maps.LatLng(37.430433,-122.17196),
    new google.maps.LatLng(37.426684,-122.165287),
	new google.maps.LatLng(37.423889,-122.169428),
    new google.maps.LatLng(37.425065,-122.171144),
    new google.maps.LatLng(37.42878,-122.173398)
  ];

function initialize() {
	var myLatlng = new google.maps.LatLng(37.42813226737076,-122.17000722885132);
	var myOptions = {
		zoom: 15,
		center: myLatlng,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	}


	map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

	drop();
	
	marker = new google.maps.Marker({
		position: myLatlng, 
		map: map,
		animation: google.maps.Animation.DROP,
		icon: image
	});

	//google.maps.event.addListener(marker, 'click', toggleBounce);
}

function drop() {
    for (var i = 0; i < foutains.length; i++) {
	 markers.push(new google.maps.Marker({
	      position: foutains[i],
	      map: map,
	      draggable: false,
	      animation: google.maps.Animation.DROP,
		  icon: image
	    }));
	 }
  }

function toggleBounce() {

	if (marker.getAnimation() != null) {
		marker.setAnimation(null);
	} else {
		marker.setAnimation(google.maps.Animation.BOUNCE);
	}
}   

</script>
<% end %>

<% content_for :maps do %>
onload="initialize()"
<% end %>
<% content_for :menu do %>

<div id="menu">
	<a href="/"><div class="item">
		<h1>how are you doing?</h1>
		see your consumption
	</div></a>
	<a href="/dashboard/charity"><div class="item">
		<h1>help us to help!</h1>
		donate
	</div></a>
	<a href="/users/edit"><div class="item">
		<h1>changes?</h1>
		edit your data
	</div></a>
	<a href="/dashboard/map"><div class="item">
		<h1>where to fill the bottle?</h1>
		map and iPhone app
	</div></a>
</div>

<% end %>

<div id="map_canvas" ></div>

app/views/dashboard/points.html.erb
<%= link_to('Logout', destroy_bottle_session_path) %>

<div id="title">
  <div class="container">

	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <%= field_set_tag do %>
    <%= f.label :email %>
	  <%= f.text_field :email %>
  <% if devise_mapping.rememberable? -%>
      <br/><%= f.check_box :remember_me %> <%= f.label :remember_me, :class => "inline"%>
	  <% end -%>

 
  <% end %>

    <%= field_set_tag do %>
      
      <%= f.label :password %>
      <%= f.text_field :password %>
    
    <% end %>

    <%= field_set_tag do %>
      <%= f.submit "Let's go" %>
      <% end %>
  <% end %>
</div>

</div>


<% if devise_mapping.rememberable? -%>
  <br/><%= f.check_box :remember_me %> <%= f.label :remember_me, :class => "inline"%>


<% end %>


<%= render :partial => "devise/shared/links" %>

app/views/dashboard/stats.html.erb
<% content_for :javascript do %>
<script src="/javascripts/raphael-min.js"></script>
<script>
window.onload = function () {
	var r = Raphael("holder", 600, 600),
	R = 200,
	init = true,
	param = {stroke: "#fff", "stroke-width": 30},
	hash = document.location.hash,
	marksAttr = {fill: hash || "#444", stroke: "none"};
	// Custom Attribute
	r.customAttributes.arc = function (value, total, R) {
		var alpha = 360 / total * value,
		a = (90 - alpha) * Math.PI / 180,
		x = 300 + R * Math.cos(a),
		y = 300 - R * Math.sin(a),
		color = "#1197cd",
		path;

		if (R == 160){
			color = "#4acd70";
		}

		if (R == 120){
			color = "#ff9d00";
		}

		if (total == value) {
			path = [["M", 300, 300 - R], ["A", R, R, 0, 1, 1, 299.99, 300 - R]];
		} else {
			path = [["M", 300, 300 - R], ["A", R, R, 0, +(alpha > 180), 1, x, y]];
		}
		return {path: path, stroke: color};
	};

	drawMarks(R, 60);
	var sec = r.path().attr(param).attr({arc: [0, 60, R]});
	R -= 40;
	drawMarks(R, 60);
	var min = r.path().attr(param).attr({arc: [0, 60, R]});
	R -= 40;
	drawMarks(R, 40);
	var hor = r.path().attr(param).attr({arc: [0, 12, R]});

	function updateVal(value, total, R, hand, id) {

		var color = "hsb(".concat(Math.round(R) / 200, ",", value / total, ", .75)");
		if (init) {
			hand.animate({arc: [value, total, R]}, 900, ">");
		} else {
			if (!value || value == total) {
				value = total;
				hand.animate({arc: [value, total, R]}, 750, "bounce", function () {
					hand.attr({arc: [0, total, R]});
				});
			} else {
				hand.animate({arc: [value, total, R]}, 750, "elastic");
			}
		}

	}

	function drawMarks(R, total) {

		var color = "hsb(".concat(Math.round(R) / 200, ", 1, .75)"),
		out = r.set();
		for (var value = 0; value < total; value++) {
			var alpha = 360 / total * value,
			a = (90 - alpha) * Math.PI / 180,
			x = 300 + R * Math.cos(a),
			y = 300 - R * Math.sin(a);
			out.push(r.circle(x, y, 2).attr(marksAttr));
		}
		return out;
	}

	// Part for the counter
	updateVal(50, 60, 200, sec, 2);
	updateVal(30, 60, 160, min, 1);
	updateVal(3, 12, 120, hor, 0);

};
</script>

<% end %>

<div id="container">
	<div id="menu">
			<%= image_tag("suez.png") %>
		
			<a href="/dashboard/index" class="left"><img src="/images/dashboard.png"></a>
			<a href="/dashboard/stats"><img src="/images/charts.png"></a>
			<a href="/dashboard/points"><img src="/images/star.png"></a>
	</div>
</div>

<div id="container">
	
	<div id="content">
		<div id="contentLeftStat">
		<div id="holder"></div>
		</div>
		<div id="contentRightStat">
			<span class="blue">1.2L of Plain Water</span><br/>
			<span class="green">0.7L of Sparkling Water</span><br/>
			<span class="orange">0.3L of Energy Water</span><br/>
			
		
		</div>
</div>
	
	
	