config/routes.rb
Awaweb::Application.routes.draw do
  
  get "oauth2/start"

  get "oauth2/callback"

  namespace(:api) do
    namespace(:v1) do
      resources :users
      resources :refills
      resources :datas
      resources :ads
      match 'refills/new/:id/:type' => 'refills#new'
      
    end
  end
  
  devise_for :users

  get "dashboard/index"

  get "dashboard/group"

  get "auth/login"

  get "auth/logout"

  resources :groups

  resources :bottles

  resources :users

  root :to => "dashboard#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
        belongs_to :user
        has_many :refills
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  # GET /bottles
  # GET /bottles.xml
  def index
    @bottles = Bottle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bottles }
    end
  end

  # GET /bottles/1
  # GET /bottles/1.xml
  def show
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bottle }
    end
  end

  # GET /bottles/new
  # GET /bottles/new.xml
  def new
    @bottle = Bottle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bottle }
    end
  end

  # GET /bottles/1/edit
  def edit
    @bottle = Bottle.find(params[:id])
  end

  # POST /bottles
  # POST /bottles.xml
  def create
    @bottle = Bottle.new(params[:bottle])
    @bottle.user_id = current_user.id
    
    respond_to do |format|
      if @bottle.save
        format.html { redirect_to(root_url) }
        format.xml  { render :xml => @bottle, :status => :created, :location => @bottle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bottles/1
  # PUT /bottles/1.xml
  def update
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      if @bottle.update_attributes(params[:bottle])
        format.html { redirect_to(@bottle, :notice => 'Bottle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.xml
  def destroy
    @bottle = Bottle.find(params[:id])
    @bottle.destroy

    respond_to do |format|
      format.html { redirect_to(bottles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="bottle">
	
    <%= f.label :serial, :class => "inline" %><br />
    <%= f.text_field :serial %>
<br/> 
    <%= f.submit "ADD BOTTLE"%>
</div>

<% end %>

app/views/bottles/edit.html.erb
<h1>Editing bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<h1>Listing bottles</h1>

<table>
  <tr>
    <th>Serial</th>
    <th>Refillnumber</th>
    <th>Cleaning</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bottles.each do |bottle| %>
  <tr>
    <td><%= bottle.serial %></td>
    <td><%= bottle.refillNumber %></td>
    <td><%= bottle.cleaning %></td>
    <td><%= link_to 'Show', bottle %></td>
    <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
    <td><%= link_to 'Destroy', bottle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/new.html.erb
<h1>Add my bottle !</h1>

<%= render 'form' %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Serial:</b>
  <%= @bottle.serial %>
</p>

<p>
  <b>Refillnumber:</b>
  <%= @bottle.refillNumber %>
</p>

<p>
  <b>Cleaning:</b>
  <%= @bottle.cleaning %>
</p>


<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>